/**
 * Template scope lock (do not remove):
 * This multi-tenant public website template is ONLY for school, junior-college, and coaching organizations.
 * Engineering colleges are excluded because they typically run large pre-existing institutional websites
 * with separate accreditation/ranking structures and BYOW onboarding.
 */
export const tenantWebsiteTemplateScope = {
  supportedOrgTypes: ["school", "junior-college", "coaching"],
  excludedOrgTypes: ["engineering-college"],
  exclusionReason:
    "Engineering colleges use BYOW flow due to their large legacy websites and accreditation-heavy content needs.",
} as const;

export const collgeWebsiteData = {
  theme: {
    primary: "#8b1d2c",
    primaryDark: "#5f1420",
    accent: "#ffffff",
    surface: "#f9fafb",
    darkSurface: "#0f172a",
  },
  institution: {
    name: "Riverview Junior College",
    shortName: "RJC",
    type: "junior-college",
    tagline: "Your Gateway to Higher Education",
    location: "Pune, Maharashtra",
    address: "Survey 14, Riverside Road, Wakad, Pune 411057",
    email: "info@riverviewjc.edu.in",
    phone: "+91 90000 12345",
    whatsapp: "+91 90000 12345",
    establishedYear: 2001,
    logoText: "Riverview",
    heroImage: "/dashboards/admin-overview.png",
  },
  hero: {
    badge: "Admissions Open 2026-27",
    headline: "Riverview Junior College",
    subHeadline: "Academic excellence with mentoring, discipline, and results",
    description:
      "Structured academics, future-ready labs, and focused guidance for board and entrance success.",
    videoUrl: "https://youtu.be/kzTWRX9Dhrg?si=Cuy0fqilgWfMpSSd",
    fallbackImages: [
      "/dashboards/results-analytics.png",
      "/dashboards/admin-overview.png",
      "/dashboards/faculty-portal.png",
    ],
    fallbackImage: "/dashboards/results-analytics.png",
    primaryCta: { label: "Apply Now", href: "/apply" },
    secondaryCta: { label: "Explore Programs", href: "/programs" },
    stats: [
      {
        key: "students",
        icon: "GraduationCap",
        value: "5400+",
        labels: {
          school: "Students Enrolled",
          "junior-college": "Students Enrolled",
          coaching: "Students Enrolled",
        },
      },
      {
        key: "results",
        icon: "Trophy",
        value: "96%",
        labels: {
          school: "Board Pass %",
          "junior-college": "HSC Result %",
          coaching: "JEE/NEET Selections",
        },
      },
      {
        key: "legacy",
        icon: "CalendarDays",
        value: "25+",
        labels: {
          school: "Years of Excellence",
          "junior-college": "Years of Excellence",
          coaching: "Years of Excellence",
        },
      },
      {
        key: "faculty",
        icon: "Users",
        value: "220+",
        labels: {
          school: "Teachers",
          "junior-college": "Faculty Members",
          coaching: "Expert Mentors",
        },
      },
    ],
  },
  navLinks: [
    { label: "Home", href: "/" },
    { label: "About", href: "/about" },
    { label: "Programs", href: "/programs" },
    { label: "Notices", href: "/notices" },
    { label: "Calendar", href: "/academic-calendar" },
    { label: "Merit", href: "/merit-list" },
    { label: "Fees", href: "/fees" },
    { label: "Students", href: "/students" },
    { label: "Downloads", href: "/downloads" },
    { label: "Events", href: "/events" },
    { label: "Blog", href: "/blog" },
    { label: "Contact", href: "/contact" },
  ],
  home: {
    highlights: [
      { icon: "Award", value: "98%", label: "Board Results", description: "Consistent distinction outcomes" },
      { icon: "BookOpen", value: "45+", label: "Programs", description: "Across streams and skill pathways" },
      { icon: "Users2", value: "220+", label: "Faculty", description: "Experienced educators and mentors" },
      { icon: "Building2", value: "50+", label: "Labs & Clubs", description: "Research, sports, and co-curriculars" },
    ],
    programsPreviewHeading: "Our Streams",
    noticesHeading: "Latest Notices",
    facultyHeading: "Meet Our Faculty Members",
    galleryHeading: "Campus Life @ Riverview",
    testimonialsHeading: "What Our Students Say",
    showQuickEnquiryFor: ["junior-college", "coaching"],
  },
  aboutPage: {
    bannerImage: "/dashboards/faculty-portal.png",
    storyTitle: "Our Story",
    story:
      "Founded in 2001, Riverview has built a culture of academic discipline and student-centric support. We combine rigorous board preparation with mentorship, practical labs, and career counseling.",
    storyImage: "/dashboards/library-system.png",
    vision:
      "To be the most trusted institution for holistic academic growth and career readiness.",
    mission:
      "Deliver strong conceptual foundations, transparent communication, and measurable outcomes for every learner.",
    principal: {
      name: "Dr. Megha Deshpande",
      designation: "Principal",
      message:
        "At Riverview, every student receives structured support and equal opportunity to succeed. Our commitment is to nurture confident, responsible, and future-ready citizens.",
      image: "/dashboards/faculty-portal.png",
    },
    accreditations: ["NAAC A+", "AICTE", "UGC Recognized", "ISO 21001", "NIRF Ranked"],
    typeSpecific: {
      school: {
        title: "Our Vision for Holistic Education",
        text: "Balanced focus on academics, sports, values, and creative growth from early years.",
      },
      "junior-college": {
        title: "Board Results & Toppers",
        text: "Stream-wise toppers and board excellence supported by revision systems and mentor tracking.",
      },
      coaching: {
        title: "Our Methodology",
        text: "Topic mastery, adaptive testing, and personalized doubt resolution to maximize selections.",
      },
    },
  },
  programsPage: {
    title: "Our Streams",
    description: "Choose the right academic track backed by expert faculty and strong exam preparation.",
    eligibilitySteps: [
      "Check eligibility criteria and intake for your preferred program.",
      "Submit the admission form with required documents.",
      "Attend counseling and complete enrollment confirmation.",
    ],
  },
  programs: [
    {
      id: "science-xi-xii",
      icon: "FlaskConical",
      group: "Science",
      name: "Science Stream (XI-XII)",
      duration: "2 Years",
      description: "Physics, Chemistry, Mathematics, and Biology with board + CET/JEE/NEET readiness.",
      subjects: ["Physics", "Chemistry", "Mathematics", "Biology"],
      intake: "240 Seats",
      eligibility: "SSC/Equivalent pass with required marks",
      schedule: "Morning + Integrated coaching options",
    },
    {
      id: "commerce-xi-xii",
      icon: "Briefcase",
      group: "Commerce",
      name: "Commerce Stream (XI-XII)",
      duration: "2 Years",
      description: "Accounting, Economics, and business fundamentals with CA/CMA orientation.",
      subjects: ["Accountancy", "Economics", "Organization of Commerce", "Mathematics"],
      intake: "180 Seats",
      eligibility: "SSC/Equivalent pass",
      schedule: "Morning and regular batches",
    },
    {
      id: "arts-xi-xii",
      icon: "Landmark",
      group: "Arts",
      name: "Arts Stream (XI-XII)",
      duration: "2 Years",
      description: "Humanities-focused curriculum with communication and social science foundations.",
      subjects: ["History", "Political Science", "Sociology", "Psychology"],
      intake: "120 Seats",
      eligibility: "SSC/Equivalent pass",
      schedule: "Day batches",
    },
  ],
  admissionBanner: {
    title: "Admissions Open 2026-27",
    description: "Secure your seat in your preferred stream before intake closes.",
    importantDates: [
      { label: "Application Start", date: "May 1, 2026" },
      { label: "Last Date to Apply", date: "June 15, 2026" },
      { label: "Merit List Publication", date: "June 22, 2026" },
    ],
    cta: { label: "Apply Now", href: "/apply" },
  },
  notices: [
    {
      id: "hsc-practical-schedule-2026",
      category: "Exam",
      title: "HSC Practical Examination Schedule Published",
      date: "2026-05-18",
      summary: "Department-wise practical dates and reporting instructions are now available.",
      body:
        "All students must check the stream-wise schedule and report 30 minutes before the assigned practical slot with hall ticket and lab records.",
      pdfUrl: "#",
    },
    {
      id: "admission-round-1-verification",
      category: "Admission",
      title: "Admission Round 1 Document Verification Window",
      date: "2026-05-12",
      summary: "Selected applicants must complete document verification this week.",
      body:
        "Candidates listed in Round 1 must bring original mark sheets, transfer certificate, and identity proof for verification at the admission desk.",
      pdfUrl: "#",
    },
    {
      id: "summer-bridge-course",
      category: "General",
      title: "Summer Bridge Course Registration Open",
      date: "2026-05-10",
      summary: "Bridge modules available for Mathematics and English foundations.",
      body:
        "The bridge course helps incoming students adapt to higher secondary coursework. Enrollment closes on May 28, 2026.",
      pdfUrl: "#",
    },
    {
      id: "campus-holiday-foundation-day",
      category: "Holiday",
      title: "Campus Holiday for Foundation Day",
      date: "2026-05-02",
      summary: "All academic operations will remain closed on Foundation Day.",
      body:
        "The campus will remain closed for all students and staff on Foundation Day. Administrative support resumes the next day.",
      pdfUrl: "#",
    },
    {
      id: "science-fair-invitations",
      category: "General",
      title: "Inter-College Science Fair Invitations",
      date: "2026-04-27",
      summary: "Project teams can submit abstracts for the annual science fair showcase.",
      body:
        "Interested teams should submit project abstracts through department coordinators. Final shortlist will be published on May 12, 2026.",
      pdfUrl: "#",
    },
  ],
  meritPage: {
    years: ["2026", "2025", "2024"],
    resultStats: [
      { label: "Pass %", value: "96%" },
      { label: "Distinctions", value: "1820" },
      { label: "First Class", value: "2840" },
      { label: "Toppers", value: "42" },
    ],
  },
  toppers: [
    {
      id: "topper-1",
      name: "Ananya Joshi",
      score: "97.8%",
      program: "Science",
      batch: "Batch of 2026",
      image: "/dashboards/student-homework.png",
    },
    {
      id: "topper-2",
      name: "Ritesh Patil",
      score: "96.9%",
      program: "Commerce",
      batch: "Batch of 2026",
      image: "/dashboards/results-analytics.png",
    },
    {
      id: "topper-3",
      name: "Mrunal Kale",
      score: "95.6%",
      program: "Arts",
      batch: "Batch of 2026",
      image: "/dashboards/attendance-dashboard.png",
    },
  ],
  meritLists: [
    {
      id: "merit-r1",
      title: "Merit List Round 1",
      program: "Science",
      round: "Round 1",
      date: "2026-06-22",
      pdfUrl: "#",
    },
    {
      id: "merit-r2",
      title: "Merit List Round 2",
      program: "Commerce",
      round: "Round 2",
      date: "2026-06-24",
      pdfUrl: "#",
    },
    {
      id: "merit-r3",
      title: "Merit List Round 3",
      program: "Arts",
      round: "Round 3",
      date: "2026-06-26",
      pdfUrl: "#",
    },
  ],
  feesPage: {
    academicYear: "2026-27",
    scholarshipTitle: "Merit Scholarships",
    scholarshipText:
      "Need-based and merit scholarships are available for eligible students. Contact the admission office for verification details.",
    policies: [
      {
        id: "rule-1",
        title: "Admission Confirmation",
        text: "Admission is confirmed only after document verification and first fee installment payment.",
      },
      {
        id: "rule-2",
        title: "Refund Policy",
        text: "Refunds follow institution policy and applicable statutory guidelines.",
      },
      {
        id: "rule-3",
        title: "Attendance Requirement",
        text: "Minimum attendance criteria must be met to appear for internal and board assessments.",
      },
    ],
  },
  fees: [
    {
      id: "fee-science",
      program: "Science Stream",
      intake: "240",
      annualFees: "INR 86,000",
      oneTimeFees: "INR 8,000",
      total: "INR 94,000",
      installments: ["INR 50,000", "INR 44,000"],
    },
    {
      id: "fee-commerce",
      program: "Commerce Stream",
      intake: "180",
      annualFees: "INR 68,000",
      oneTimeFees: "INR 7,000",
      total: "INR 75,000",
      installments: ["INR 40,000", "INR 35,000"],
    },
    {
      id: "fee-arts",
      program: "Arts Stream",
      intake: "120",
      annualFees: "INR 54,000",
      oneTimeFees: "INR 6,000",
      total: "INR 60,000",
      installments: ["INR 32,000", "INR 28,000"],
    },
  ],
  faculty: [
    {
      id: "faculty-1",
      name: "Prof. Nandini Gokhale",
      designation: "Vice Principal",
      department: "Science",
      subject: "Physics",
      image: "/dashboards/faculty-portal.png",
    },
    {
      id: "faculty-2",
      name: "Prof. Aditya Kulkarni",
      designation: "HOD Commerce",
      department: "Commerce",
      subject: "Accountancy",
      image: "/dashboards/student-homework.png",
    },
    {
      id: "faculty-3",
      name: "Prof. Sneha Patankar",
      designation: "HOD Arts",
      department: "Arts",
      subject: "Psychology",
      image: "/dashboards/attendance-dashboard.png",
    },
    {
      id: "faculty-4",
      name: "Prof. Rohit Deshmukh",
      designation: "Academic Coordinator",
      department: "Science",
      subject: "Mathematics",
      image: "/dashboards/results-analytics.png",
    },
    {
      id: "faculty-5",
      name: "Prof. Sachi Bendre",
      designation: "Senior Lecturer",
      department: "Commerce",
      subject: "Economics",
      image: "/dashboards/lead-crm.png",
    },
    {
      id: "faculty-6",
      name: "Prof. Neeraj Kulshreshtha",
      designation: "Senior Lecturer",
      department: "Arts",
      subject: "History",
      image: "/dashboards/library-system.png",
    },
  ],
  gallery: {
    categories: ["All", "Campus", "Events", "Sports", "Academics", "Annual Day"],
    images: [
      { id: "g1", category: "Campus", image: "/dashboards/admin-overview.png", title: "Main Campus" },
      { id: "g2", category: "Academics", image: "/dashboards/faculty-portal.png", title: "Smart Classroom" },
      { id: "g3", category: "Events", image: "/dashboards/alumni-network.png", title: "Cultural Fest" },
      { id: "g4", category: "Sports", image: "/dashboards/attendance-dashboard.png", title: "Sports Day" },
      { id: "g5", category: "Annual Day", image: "/dashboards/results-analytics.png", title: "Annual Day" },
      { id: "g6", category: "Campus", image: "/dashboards/library-system.png", title: "Library" },
      { id: "g7", category: "Events", image: "/dashboards/lead-crm.png", title: "Seminar" },
      { id: "g8", category: "Academics", image: "/dashboards/student-homework.png", title: "Lab Session" },
      { id: "g9", category: "Campus", image: "/dashboards/exam-auto-grade.png", title: "Innovation Lab" },
      { id: "g10", category: "Sports", image: "/dashboards/bus-tracking.png", title: "Ground" },
      { id: "g11", category: "Annual Day", image: "/dashboards/certificate-printing.png", title: "Awards" },
      { id: "g12", category: "Events", image: "/dashboards/naac-nba.png", title: "Achievement Meet" },
    ],
    videos: [
      {
        id: "v1",
        title: "Campus Tour",
        youtubeUrl: "https://www.youtube.com/embed/aqz-KE-bpKQ",
        thumbnail: "/dashboards/admin-overview.png",
      },
      {
        id: "v2",
        title: "Annual Day Highlights",
        youtubeUrl: "https://www.youtube.com/embed/5qap5aO4i9A",
        thumbnail: "/dashboards/alumni-network.png",
      },
    ],
  },
  testimonials: [
    {
      id: "t1",
      name: "Mrunal Pophale",
      batch: "Science, 2024",
      program: "Science Stream",
      rating: 5,
      text:
        "Faculty mentoring and regular test analytics gave me confidence and a clear plan for board preparation.",
      image: "/dashboards/student-homework.png",
      facebook: "#",
      linkedin: "#",
    },
    {
      id: "t2",
      name: "Om Bidve",
      batch: "Commerce, 2025",
      program: "Commerce Stream",
      rating: 5,
      text:
        "The campus environment is focused and supportive. Doubt-solving sessions helped me improve each week.",
      image: "/dashboards/results-analytics.png",
      facebook: "#",
      linkedin: "#",
    },
    {
      id: "t3",
      name: "Pooja Katpale",
      batch: "Arts, 2024",
      program: "Arts Stream",
      rating: 5,
      text:
        "Teachers encouraged us to build communication and confidence, not just marks. That made a big difference.",
      image: "/dashboards/attendance-dashboard.png",
      facebook: "#",
      linkedin: "#",
    },
  ],
  eventsPage: {
    categories: ["All", "Technical", "Cultural", "Sports", "Academic", "Annual"],
  },
  events: [
    {
      slug: "innovation-fair-2026",
      title: "Innovation Fair 2026",
      category: "Technical",
      status: "Upcoming",
      date: "2026-08-14",
      time: "10:00 AM",
      venue: "Innovation Arena",
      image: "/dashboards/ai-proctoring.png",
      summary: "Student-led innovation showcase with prototypes, demos, and jury sessions.",
      description:
        "Innovation Fair 2026 brings cross-stream student teams together for prototype demonstrations, technology showcases, and collaboration with industry mentors.",
      registerLabel: "Register Now",
      schedule: [
        { time: "10:00 AM", title: "Opening Ceremony" },
        { time: "11:00 AM", title: "Prototype Presentation" },
        { time: "2:30 PM", title: "Jury Round" },
        { time: "5:30 PM", title: "Awards" },
      ],
      gallery: [
        "/dashboards/ai-proctoring.png",
        "/dashboards/lead-crm.png",
        "/dashboards/results-analytics.png",
        "/dashboards/library-system.png",
      ],
    },
    {
      slug: "annual-day-2026",
      title: "Annual Day Celebration",
      category: "Cultural",
      status: "Upcoming",
      date: "2026-12-10",
      time: "6:00 PM",
      venue: "Main Auditorium",
      image: "/dashboards/alumni-network.png",
      summary: "A celebration of student achievements, performances, and annual honors.",
      description:
        "Annual Day celebrates academic and cultural excellence with performances, awards, and parent engagement.",
      registerLabel: "Know More",
      schedule: [
        { time: "6:00 PM", title: "Welcome Address" },
        { time: "6:30 PM", title: "Student Performances" },
        { time: "8:30 PM", title: "Awards and Closing" },
      ],
      gallery: [
        "/dashboards/alumni-network.png",
        "/dashboards/admin-overview.png",
        "/dashboards/student-homework.png",
      ],
    },
    {
      slug: "sports-meet-2026",
      title: "Sports Meet 2026",
      category: "Sports",
      status: "Past",
      date: "2026-01-20",
      time: "8:00 AM",
      venue: "College Ground",
      image: "/dashboards/attendance-dashboard.png",
      summary: "Inter-house sports events and fitness competitions across disciplines.",
      description:
        "The annual sports meet featured athletics, team sports, and skill competitions with strong student participation.",
      registerLabel: "Event Completed",
      schedule: [
        { time: "8:00 AM", title: "March Past" },
        { time: "9:30 AM", title: "Track Events" },
        { time: "3:30 PM", title: "Prize Distribution" },
      ],
      gallery: [
        "/dashboards/attendance-dashboard.png",
        "/dashboards/bus-tracking.png",
        "/dashboards/admin-overview.png",
      ],
    },
  ],
  alumniPage: {
    heading: "Our Alumni - Their Success, Our Pride",
    successStoriesHeading: "Success Stories",
    connectHeading: "Are you our alumnus? Register with us",
  },
  alumni: [
    {
      id: "a1",
      name: "Rhea Nair",
      batchYear: "2020",
      program: "Science",
      currentOrg: "IIT Bombay",
      city: "Mumbai",
      achievement: "Gold medal in undergraduate research symposium",
      quote: "The college mentoring system helped me build consistency and confidence.",
      linkedin: "#",
      image: "/dashboards/results-analytics.png",
    },
    {
      id: "a2",
      name: "Karan Shinde",
      batchYear: "2019",
      program: "Commerce",
      currentOrg: "Deloitte",
      city: "Pune",
      achievement: "Fast-track promotion in audit and advisory",
      quote: "Communication and leadership opportunities at campus shaped my career path.",
      linkedin: "#",
      image: "/dashboards/lead-crm.png",
    },
    {
      id: "a3",
      name: "Sakshi Kulkarni",
      batchYear: "2021",
      program: "Arts",
      currentOrg: "Symbiosis University",
      city: "Pune",
      achievement: "Topper in social sciences",
      quote: "Faculty guidance gave me a strong foundation for higher studies.",
      linkedin: "#",
      image: "/dashboards/student-homework.png",
    },
  ],
  blogPage: {
    categories: ["All", "News", "Academic", "Events", "Tips"],
  },
  blogPosts: [
    {
      slug: "how-to-prepare-for-hsc-board-exams",
      category: "Academic",
      title: "How to Prepare for HSC Board Exams with a Weekly System",
      excerpt:
        "A practical routine to balance theory revision, tests, and confidence-building during board season.",
      image: "/dashboards/results-analytics.png",
      author: "Editorial Team",
      authorRole: "Academic Cell",
      date: "2026-04-10",
      content: [
        "Build a weekly routine that includes concept review, writing practice, and one timed test per subject.",
        "Track mistakes in a revision log so the same errors do not repeat in final exams.",
        "Use short daily recap blocks to strengthen retention and avoid last-week pressure.",
      ],
    },
    {
      slug: "five-parent-student-alignment-practices",
      category: "Tips",
      title: "Five Parent-Student Alignment Practices that Improve Results",
      excerpt:
        "Simple communication habits that keep families informed and students focused throughout the term.",
      image: "/dashboards/lead-crm.png",
      author: "Counseling Desk",
      authorRole: "Student Support",
      date: "2026-03-28",
      content: [
        "Set one fixed weekly check-in where progress and blockers are discussed calmly.",
        "Focus on effort trends and consistency rather than daily score fluctuations.",
        "Align on realistic short milestones to maintain motivation.",
      ],
    },
    {
      slug: "inside-our-lab-learning-model",
      category: "News",
      title: "Inside Our Lab-Integrated Learning Model",
      excerpt:
        "How practical lab blocks and concept workshops strengthen classroom learning outcomes.",
      image: "/dashboards/library-system.png",
      author: "Prof. Nandini Gokhale",
      authorRole: "Vice Principal",
      date: "2026-03-16",
      content: [
        "Lab-integrated learning helps students connect textbook concepts with practical application.",
        "Weekly practical reviews and oral viva sessions improve conceptual clarity.",
        "This model supports both board results and entrance preparation.",
      ],
    },
  ],
  contactPage: {
    officeHours: "Monday to Saturday: 9:00 AM - 5:00 PM",
    mapEmbedUrl: "https://www.google.com/maps?q=Pune%20Maharashtra&output=embed",
  },
  applyPage: {
    heading: "Apply for Admissions 2026-27",
    confirmationPrefix: "CG",
    stepTitles: ["Basic Info", "Academic Info", "Submit"],
  },
  mandatoryDisclosurePage: {
    institutionDetails: [
      { label: "Institution Name", value: "Riverview Junior College" },
      { label: "UDISE / College Code", value: "MH-RJC-2026-1142" },
      { label: "Established", value: "2001" },
      { label: "Address", value: "Survey 14, Riverside Road, Wakad, Pune 411057" },
      { label: "Principal", value: "Dr. Megha Deshpande" },
    ],
    trustDetails: [
      { label: "Trust / Society", value: "Riverview Education Trust" },
      { label: "Registration No", value: "TRUST/PN/2000/8842" },
      { label: "PAN", value: "AAATR1234K" },
      { label: "Contact", value: "+91 90000 12345" },
    ],
    affiliationDetails: [
      { label: "Board", value: "Maharashtra State Board" },
      { label: "Affiliation Number", value: "HSC-PN-7788" },
      { label: "Academic Session", value: "2026-27" },
      { label: "Recognition Validity", value: "Till March 31, 2028" },
    ],
    infrastructureDetails: [
      { label: "Classrooms", value: "42 Smart Classrooms" },
      { label: "Laboratories", value: "12 Physics/Chemistry/Biology/Computer Labs" },
      { label: "Library", value: "24,500 Books + E-Library Access" },
      { label: "Sports", value: "Ground, Indoor Hall, Gymnasium" },
      { label: "Safety", value: "CCTV, Fire Safety, Medical Room" },
    ],
    staffDetails: [
      { label: "Teaching Staff", value: "220" },
      { label: "Non-Teaching Staff", value: "84" },
      { label: "Counselors", value: "6" },
      { label: "Lab Assistants", value: "18" },
    ],
    committees: [
      { name: "Grievance Redressal Committee", contact: "grievance@riverviewjc.edu.in" },
      { name: "Internal Complaints Committee (ICC)", contact: "icc@riverviewjc.edu.in" },
      { name: "Anti-Ragging Committee", contact: "antiragging@riverviewjc.edu.in" },
      { name: "SC/ST Committee", contact: "inclusion@riverviewjc.edu.in" },
      { name: "Student Welfare Committee", contact: "welfare@riverviewjc.edu.in" },
    ],
    documents: [
      { title: "Recognition Certificate", category: "Recognition", url: "#" },
      { title: "Affiliation Letter", category: "Affiliation", url: "#" },
      { title: "Trust Registration Certificate", category: "Trust", url: "#" },
      { title: "Fire & Safety NOC", category: "Safety", url: "#" },
      { title: "Building Safety Certificate", category: "Infrastructure", url: "#" },
    ],
  },
  committeesPage: {
    description: "Statutory and institutional committees that ensure safety, inclusion, and transparent grievance handling.",
    committees: [
      {
        id: "committee-grievance",
        name: "Grievance Redressal Committee",
        purpose: "Handles student and parent grievances with structured timelines.",
        chairperson: "Prof. Nandini Gokhale",
        members: "Academic coordinator, counselor, parent representative",
        contact: "grievance@riverviewjc.edu.in",
      },
      {
        id: "committee-anti-ragging",
        name: "Anti-Ragging Committee",
        purpose: "Prevents and addresses ragging incidents across campus.",
        chairperson: "Prof. Rohit Deshmukh",
        members: "Vice principal, discipline head, student council lead",
        contact: "antiragging@riverviewjc.edu.in",
      },
      {
        id: "committee-icc",
        name: "Internal Complaints Committee (ICC)",
        purpose: "Addresses gender-related complaints and awareness initiatives.",
        chairperson: "Prof. Sneha Patankar",
        members: "Women faculty, legal advisor, NGO external member",
        contact: "icc@riverviewjc.edu.in",
      },
      {
        id: "committee-scst",
        name: "SC/ST Committee",
        purpose: "Supports inclusive policy implementation and grievance redressal.",
        chairperson: "Prof. Neeraj Kulshreshtha",
        members: "Faculty, welfare officer, community representative",
        contact: "inclusion@riverviewjc.edu.in",
      },
    ],
  },
  infrastructurePage: {
    description: "High-quality learning spaces and safety-first facilities designed for academic rigor and student wellbeing.",
    facilities: [
      {
        id: "infra-classrooms",
        title: "Smart Classrooms",
        description: "Digitally enabled classrooms with projector systems and lecture capture support.",
        image: "/dashboards/admin-overview.png",
        highlights: ["42 classrooms", "AV-enabled", "Daily maintenance cycle"],
      },
      {
        id: "infra-labs",
        title: "Laboratories",
        description: "Dedicated labs for science and computer practicals with supervised sessions.",
        image: "/dashboards/exam-auto-grade.png",
        highlights: ["12 labs", "Weekly practical schedule", "Lab assistant support"],
      },
      {
        id: "infra-library",
        title: "Library & Reading Hall",
        description: "Central library with print resources, journals, and digital reference subscriptions.",
        image: "/dashboards/library-system.png",
        highlights: ["24,500 books", "E-library access", "Silent reading zones"],
      },
      {
        id: "infra-sports",
        title: "Sports & Fitness",
        description: "Outdoor and indoor facilities to support holistic development.",
        image: "/dashboards/attendance-dashboard.png",
        highlights: ["Athletics ground", "Indoor hall", "Structured sports calendar"],
      },
      {
        id: "infra-safety",
        title: "Campus Safety",
        description: "Round-the-clock monitoring and compliance-ready safety systems.",
        image: "/dashboards/naac-nba.png",
        highlights: ["CCTV surveillance", "Fire safety systems", "On-campus first aid room"],
      },
    ],
  },
  academicCalendarPage: {
    year: "2026-27",
    description: "Key academic milestones, examinations, holidays, and parent-facing dates for the active academic year.",
    entries: [
      { id: "cal-1", title: "Academic Session Begins", category: "Academic", startDate: "2026-06-15", endDate: "2026-06-15" },
      { id: "cal-2", title: "Unit Test 1", category: "Examination", startDate: "2026-07-20", endDate: "2026-07-25" },
      { id: "cal-3", title: "PTM - Term 1", category: "Parent Meeting", startDate: "2026-08-08", endDate: "2026-08-08" },
      { id: "cal-4", title: "Mid-Term Examination", category: "Examination", startDate: "2026-09-14", endDate: "2026-09-24" },
      { id: "cal-5", title: "Diwali Vacation", category: "Holiday", startDate: "2026-11-02", endDate: "2026-11-08" },
      { id: "cal-6", title: "Pre-Board / Preliminary", category: "Examination", startDate: "2027-01-04", endDate: "2027-01-16" },
    ],
    downloads: [
      { label: "Academic Calendar PDF (2026-27)", url: "#" },
      { label: "Exam Planner PDF", url: "#" },
    ],
  },
  syllabusPage: {
    description: "Program-wise curriculum and syllabus documents for classroom planning and exam preparation.",
    groups: [
      {
        id: "syllabus-school",
        title: "School Syllabus (Class-wise)",
        orgTypes: ["school"],
        items: [
          { name: "Class 9 Syllabus", pdfUrl: "#" },
          { name: "Class 10 Syllabus", pdfUrl: "#" },
          { name: "Class 11 Syllabus", pdfUrl: "#" },
          { name: "Class 12 Syllabus", pdfUrl: "#" },
        ],
      },
      {
        id: "syllabus-junior",
        title: "Junior College Syllabus (Stream-wise)",
        orgTypes: ["junior-college"],
        items: [
          { name: "Science Stream Syllabus", pdfUrl: "#" },
          { name: "Commerce Stream Syllabus", pdfUrl: "#" },
          { name: "Arts Stream Syllabus", pdfUrl: "#" },
        ],
      },
      {
        id: "syllabus-coaching",
        title: "Coaching Curriculum (Batch-wise)",
        orgTypes: ["coaching"],
        items: [
          { name: "JEE Main Foundation Module", pdfUrl: "#" },
          { name: "JEE Advanced Practice Plan", pdfUrl: "#" },
          { name: "NEET Integrated Module", pdfUrl: "#" },
        ],
      },
    ],
  },
  examinationsPage: {
    description: "Assessment framework, internal test patterns, and board-exam readiness structure.",
    patterns: [
      { title: "Unit Test Pattern", details: "Topic-wise tests every 4-6 weeks with performance analytics." },
      { title: "Mid-Term / Semester Pattern", details: "Structured exams aligned to board blueprint and practicals." },
      { title: "Prelim / Mock Exams", details: "Full-length model papers with time-bound evaluation." },
    ],
    assessments: [
      { title: "Theory Examinations", weightage: "70%" },
      { title: "Practical / Viva", weightage: "20%" },
      { title: "Internal Assessment", weightage: "10%" },
    ],
    schedules: [
      { name: "Unit Test 1", date: "2026-07-20" },
      { name: "Unit Test 2", date: "2026-08-26" },
      { name: "Mid-Term Exam", date: "2026-09-14" },
      { name: "Preliminary Exam", date: "2027-01-04" },
    ],
    downloads: [
      { label: "Examination Manual", url: "#" },
      { label: "Board Exam Guidelines", url: "#" },
    ],
  },
  studentsPage: {
    description: "Student Corner gives quick access to essential academic and campus information without login.",
    quickLinks: [
      { label: "Notices", href: "/notices", description: "Latest circulars and urgent updates" },
      { label: "Merit & Results", href: "/merit-list", description: "Published merit lists and result stats" },
      { label: "Academic Calendar", href: "/academic-calendar", description: "Important dates and holidays" },
      { label: "Downloads", href: "/downloads", description: "Prospectus, forms, timetables, and circulars" },
      { label: "Examinations", href: "/examinations", description: "Assessment pattern and exam schedule" },
      { label: "Syllabus", href: "/syllabus", description: "Program-wise curriculum resources" },
    ],
    parentCorner: [
      { label: "PTM Schedule", value: "Second Saturday of every month" },
      { label: "School/College Timings", value: "8:00 AM - 2:30 PM" },
      { label: "Transport Helpline", value: "+91 90000 12346" },
      { label: "Child Safety Policy", value: "Published in Downloads section" },
    ],
    studentPolicies: [
      "Code of conduct and attendance policy",
      "Anti-ragging and anti-bullying declaration",
      "Grievance redressal process with committee contacts",
    ],
  },
  downloadsPage: {
    description: "Centralized repository for admission, academics, examinations, and policy documents.",
    categories: ["All", "Admission", "Academic", "Examination", "Policy"],
    resources: [
      { id: "dl-1", title: "Admission Form 2026-27", category: "Admission", date: "2026-04-20", url: "#" },
      { id: "dl-2", title: "College Prospectus", category: "Admission", date: "2026-04-22", url: "#" },
      { id: "dl-3", title: "Academic Calendar PDF", category: "Academic", date: "2026-05-01", url: "#" },
      { id: "dl-4", title: "Unit Test Timetable", category: "Examination", date: "2026-06-15", url: "#" },
      { id: "dl-5", title: "Fee Circular", category: "Academic", date: "2026-06-20", url: "#" },
      { id: "dl-6", title: "Student Safety Policy", category: "Policy", date: "2026-05-28", url: "#" },
      { id: "dl-7", title: "Anti-Ragging Undertaking", category: "Policy", date: "2026-05-28", url: "#" },
      { id: "dl-8", title: "Board Exam Guidelines", category: "Examination", date: "2026-10-02", url: "#" },
    ],
  },
  quickEnquiry: {
    heading: "Quick Enquiry",
    description: "Share your details and our admissions team will contact you within 24 hours.",
  },
  socialLinks: [
    { label: "Facebook", href: "#", platform: "facebook" },
    { label: "Instagram", href: "#", platform: "instagram" },
    { label: "LinkedIn", href: "#", platform: "linkedin" },
    { label: "YouTube", href: "#", platform: "youtube" },
    { label: "WhatsApp", href: "#", platform: "whatsapp" },
  ],
  footer: {
    academicsLinks: [
      { label: "Programs", href: "/programs" },
      { label: "Faculty", href: "/about" },
      { label: "Gallery", href: "/gallery" },
      { label: "Events", href: "/events" },
      { label: "Alumni", href: "/alumni" },
      { label: "Blog", href: "/blog" },
    ],
    quickLinks: [
      { label: "Notices", href: "/notices" },
      { label: "Merit List", href: "/merit-list" },
      { label: "Admissions", href: "/apply" },
      { label: "Fees", href: "/fees" },
      { label: "Student Corner", href: "/students" },
      { label: "Downloads", href: "/downloads" },
      { label: "Academic Calendar", href: "/academic-calendar" },
      { label: "Syllabus", href: "/syllabus" },
      { label: "Mandatory Disclosure", href: "/mandatory-disclosure" },
      { label: "Committees", href: "/committees" },
      { label: "Infrastructure", href: "/infrastructure" },
      { label: "Contact", href: "/contact" },
      { label: "Portal Login", href: "/apply" },
    ],
    legalLinks: [
      { label: "Privacy Policy", href: "/contact" },
      { label: "Terms of Use", href: "/contact" },
    ],
    newsletterCta: "Subscribe",
  },
};
